reddit_clone/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :subs 
  resource :session, only: [:new, :create, :destroy] 
  resources :users, only: [:new, :create] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :author_id, presence: true 
  validate :has_sub?

  has_many :post_subs, inverse_of: :post 

  has_many :subs,
  through: :post_subs,
  source: :sub 
  
  
  belongs_to :author,
  foreign_key: :author_id,
  class_name: :User 

  def has_sub?
    !self.subs.empty?    
  end 

end

reddit_clone/app/models/post_sub.rb
class PostSub < ApplicationRecord 
  
  belongs_to :post 

  belongs_to :sub 


end 

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true 
  
  belongs_to :moderator,
  foreign_key: :moderator_id,
  class_name: :User

  
  has_many :post_subs, inverse_of: :sub

  has_many :posts, 
  through: :post_subs,
  source: :post


end

reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#

class User < ApplicationRecord
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(password)
    user
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  has_many :subs,
  foreign_key: :moderator_id,
  class_name: :Sub
  
  has_many :posts,
  foreign_key: :author_id,
  class_name: :Post 


end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :logged_in?, :current_user

def current_user
  @current ||= User.find_by(session_token: session[:session_token])
end 

def ensure_logged_in 
  redirect_to new_session_url unless logged_in? 
end 

def login(user)
  session[:session_token] = user.reset_session_token! 
end 

def logout
  current_user.reset_session_token!
  @current_user = nil 
  session[:session_token] = nil 
end 

def logged_in?
  !!current_user
end

def is_moderator?
  self.moderator_id == current_user.id
end

end

reddit_clone/app/controllers/post_subs_controller.rb
class PostSubsController < ApplicationController
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_logged_in 

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id]) 
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
      if @post.save
        # params[:sub_ids].each do |id|
        #   PostSub.create(sub_id: id, post_id: @post.id)
        # end
        redirect_to post_url(@post) 
      else
        flash.now[:errors] = @post.errors.full_messages
        render :new 
      end
    
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
      @post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to post_url(@post) 
      else
        flash.now[:errors] = @post.errors.full_messages
        render :edit 
      end
    
  end
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :content, sub_ids:[]) 
    end
end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end 

def create
  @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
  if @user 
    login(@user) 
    redirect_to subs_url
  else 
    flash.now[:errors] = "Invalid Credentials"
    render :new 
  end 
end 

def destroy
  logout
  redirect_to new_session_url 
end 


end 

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_logged_in
  before_action :is_moderator?, only: [:edit, :update]

  # GET /subs
  # GET /subs.json
  def index
    @subs = Sub.all
  end

  # GET /subs/1
  # GET /subs/1.json
  def show
    @sub = Sub.find(params[:id])
  end

  # GET /subs/new
  def new
    @sub = Sub.new
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  # POST /subs
  # POST /subs.json
  def create
    @sub = Sub.new(sub_params)  
    @sub.moderator_id = current_user.id 
      if @sub.save
        redirect_to sub_url(@sub)
      else
        flash.now[:errors] = @sub.errors.full_messages 
        render :new 
      end    
  end

  # PATCH/PUT /subs/1
  # PATCH/PUT /subs/1.json
  def update
    @sub = Sub.find(params[:id]) ## 
      if @sub.update(sub_params)
        redirect_to sub_url(@sub)
      else
         flash.now[:errors] = @sub.errors.full_messages 
        render :edit 
      end
    
  end

  # DELETE /subs/1
  # DELETE /subs/1.json
  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url 
  end

  private
    def sub_params
      params.require(:sub).permit(:title, :description)
    end
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user) 
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages 
      render :new 
    end 
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>




  <% if logged_in? %>
  <%= current_user.username %>
  <%= link_to 'Create a sub!', new_sub_url  %>
  <%= link_to 'All Subs', subs_url  %>
    <form action="<%= session_url %>", method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit"  value="Sign Out">
    </form>
  <% else %>
  <p>
  <%= link_to 'Sign In', new_session_url %>
  </p>
  <% end %>



    <%= yield %>
  </body>
</html>

reddit_clone/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

reddit_clone/app/views/posts/edit.html.erb
<h1>Edit Post!</h1>

<form action="<%= post_url(@post) %>" method="POST">
<input type="hidden" name="_method" value="PATCH">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<label for="title">Title</label>
<input type="text" name="post[title]" id="title" value="<%= @post.title %>">
<label for="url">URL</label>
<input type="text" name="post[url]" id="url" value="<%= @post.title %>">
<label for="content">Content</label>
<textarea name="post[content]" id="content" cols="30" rows="10"><%= @post.content %></textarea>

<% Sub.all.each do |subo| %>
<label>
<input
  type="checkbox"
  name="post[sub_ids][]"
  value="<%= subo.id %>"
  <%= "checked" if @post.sub_ids.include?(subo.id) %>>   
  <%= subo.title %>
</label>
<% end %>
<input type="submit" value="Submit">
</form>

reddit_clone/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

reddit_clone/app/views/posts/new.html.erb
<h1>New Post!</h1>

<form action="<%= posts_url %>" method="POST">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<label for="title">Title</label>
<input type="text" name="post[title]" id="title">
<label for="url">URL</label>
<input type="text" name="post[url]" id="url">
<label for="content">Content</label>
<textarea name="post[content]" id="content" cols="30" rows="10"></textarea>

<% Sub.all.each do |subo| %>
<label>
<input type="checkbox" name="post[sub_ids][]" value="<%= subo.id %>">
<%= subo.title %>
</label>
<% end %>
<input type="submit" value="Submit">
</form>

reddit_clone/app/views/posts/show.html.erb
<h2><%= @post.title %> by <%= @post.author.username %></h2>

<p>Content</p>
<p><%= @post.content %></p>


<strong>Subs</strong>
<ul>
<% @post.subs.each do |sub| %>
<li><%= link_to sub.title, sub_url(sub) %></li>
<% end %>
</ul>

<h2>Comments</h2>

<%= link_to 'Edit', edit_post_url(@post) %>

reddit_clone/app/views/subs/_form.html.erb
<%= form_with(model: sub, local: true) do |form| %>
  <% if sub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub.errors.count, "error") %> prohibited this sub from being saved:</h2>

      <ul>
      <% sub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

reddit_clone/app/views/subs/edit.html.erb
<h1>Editing Sub</h1>

<%= render 'form', sub: @sub %>

<%= link_to 'Show', @sub %> |
<%= link_to 'Back', subs_path %>

reddit_clone/app/views/subs/index.html.erb
<h2>All the Subs</h2>
<ul>
<% @subs.each do |sub| %>
<li><%= link_to sub.title, sub_url(sub) %></li>
<% end %>  
</ul>

<p></p><%= link_to 'Create Sub', new_sub_url %>

reddit_clone/app/views/subs/new.html.erb
<h2>Create a new sub!</h2>

<form action="<%= subs_url %>" method="POST">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label for="title">Name</label>
<input type="text" name="sub[title]" id="title">
<label for="description">Description</label>
<input type="text" name="sub[description]" id="description">
<input type="submit" value="Submit!" > 
</form>

reddit_clone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1> 
<p><strong>Description</strong></p>
<p><%= @sub.description %></p>

<%= link_to 'Make New Post!', new_post_url %>

<ul>
<% @sub.posts.each do |post| %>
<li><%= link_to post.title, post_url(post) %></li>
<% end %>
</ul>

reddit_clone/app/views/users/new.html.erb
<h2>New User!</h2>

<form action="<%= users_url %>" method="POST">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label for="username">Username</label>
<input type="text" name="user[username]" id="username">
<label for="password">Password</label>
<input type="text" name="user[password]" id="password">
<input type="submit" value="create user" > 

</form>